services:
  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    container_name: zap
    command: zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
    ports:
      - "8080:8080"
    networks:
      - vuln-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  backend:
    build: 
      context: ./backend
      dockerfile: docker/Dockerfile
    container_name: vuln-backend
    volumes:
      - ./backend:/app
    depends_on:
      zap:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      - ZAP_API_URL=http://zap:8080
      - ZAP_API_KEY=
    networks:
      - vuln-net

  vulnui:
    build: 
      context: ./vulnui
      dockerfile: docker/Dockerfile
    container_name: vulnui
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - vuln-net

networks:
  vuln-net:
    driver: bridge
